<template>
  <div v-if="false" id="my-stacks">
    <h2>Mais detalhes (Lang's, Tecnologias)</h2>
    <h3>Tecnologias</h3>
    <h4>Languages:</h4>
    <p>
      <img
        src="https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54"
        alt="Python"
      />
      <img
        src="https://img.shields.io/badge/c-%2300599C.svg?style=for-the-badge&logo=c&logoColor=white"
        alt="C"
      />
      <img
        src="https://img.shields.io/badge/c++-%2300599C.svg?style=for-the-badge&logo=c%2B%2B&logoColor=white"
        alt="C++"
      />
      <img
        src="https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E"
        alt="JavaScript"
      />
      <img
        src="https://img.shields.io/badge/PowerShell-%235391FE.svg?style=for-the-badge&logo=powershell&logoColor=white"
        alt="PowerShell"
      />
    </p>
    <h4>Libraries e Frameworks:</h4>
    <p>
      <img
        src="https://img.shields.io/badge/jquery-%230769AD.svg?style=for-the-badge&logo=jquery&logoColor=white"
        alt="jQuery"
      />
      <img
        src="https://img.shields.io/badge/bootstrap-%238511FA.svg?style=for-the-badge&logo=bootstrap&logoColor=white"
        alt="Bootstrap"
      />
      <img
        src="https://img.shields.io/badge/flask-%23000.svg?style=for-the-badge&logo=flask&logoColor=white"
        alt="Flask"
      />
      <img
        src="https://img.shields.io/badge/-selenium-%43B02A?style=for-the-badge&logo=selenium&logoColor=white"
        alt="Selenium"
      />
      <img
        src="https://img.shields.io/badge/Electron-191970?style=for-the-badge&logo=Electron&logoColor=white"
        alt="Electron.js"
      />
      <img
        src="https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white"
        alt="NodeJS"
      />
    </p>
    <h4>Databases:</h4>
    <p>
      <img
        src="https://img.shields.io/badge/postgres-%23316192.svg?style=for-the-badge&logo=postgresql&logoColor=white"
        alt="Postgres"
      />
      <img
        src="https://img.shields.io/badge/mysql-4479A1.svg?style=for-the-badge&logo=mysql&logoColor=white"
        alt="MySQL"
      />
    </p>
    <h4>Sistemas:</h4>
    <p>
      <img
        src="https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white"
        alt="Windows"
      />
      <img
        src="https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black"
        alt="Linux"
      />
    </p>
  </div>
</template>
