#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Nicholas Silva'
        hostname: iridium;
        username:  robotz213
        password: "$y$j9T$PLlUUns1wU9qufUBofpMS.$o7yK.FK/fKF2.y/pi6zlxLDoj7b8Uj2O1cwHaTkKPT5"
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - wget
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
