on:
    release:
        types: [published]

name: 🚀 Deploy website on push
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2
  
        - name: 📂 Sync files
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
            ARGS: "-rltgoDzvO --delete"
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_USER: ${{ secrets.SSH_USER}}
            REMOTE_PORT: ${{ secrets.SSH_PORT }}
            TARGET: ${{ secrets.SSH_TARGET }}
            SCRIPT_BEFORE: |
                echo "
                    [Unit]
                    Description=Python Service
                    After=network.target
                    
                    [Service]
                    User=${{ secrets.SSH_USER}}
                    WorkingDirectory= ${{ secrets.SSH_TARGET }}
                    ExecStart= poetry run python ${{ secrets.SSH_TARGET }}/main.py
                    Restart=always
                    
                    [Install]
                    WantedBy=multi-user.target
                    " | tee /etc/systemd/system/flask_app.service
                    systemctl daemon-reload
                    
            SCRIPT_AFTER: |
                    cd ${{ secrets.SSH_TARGET }}
                    poetry install
                    systemctl enable flask_app.service
                    systemctl starte flask_app.service
                    
            
