on:
    release:
        types: [published]

name: 🚀 Deploy website on push
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v2
  
        - name: 📂 Sync files
          uses: easingthemes/ssh-deploy@main
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
            ARGS: "-rltgoDzvO --delete"
            REMOTE_HOST: ${{}}
            REMOTE_USER: ${{}}
            REMOTE_PORT: ${{}}
            REMOTE_TARGET: ${{}}
